#!/usr/bin/env python3

import colors as c

print(c.red + '''
Who would cross the Bridge of Death
must answer me these questions three
'Ere the other side he see.
''' + c.reset)

def prompt(question):
    print(question)
    answer = input(c.red + '> ')
    print(c.reset)
    return answer

name = prompt('What is your name? ')
quest = prompt('What is your quest? ')
color = prompt('What is your favorite color? ')

if name == 'Lancelot' or name == 'Galahad':
    color = prompt('What is your favorite color? ')
